export interface ITabledata{
    "SL.No": number,
    "Industry Category": string,
    "Industry Code": string,
    "industryName":string,
    "Full Address":string,
    "Contact in which SMSAlerts generated": number,
    "State": string,
    "Station Name": string,
    "Parameter Standard limit's": number,
    "Parameter": string,
    "Excedence": number,
    "Total SMS": number,
    "In Ganga Basin": string,
}